# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('A_ID', models.AutoField(primary_key=True, serialize=False)),
                ('A_text', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Q_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Q_type', models.CharField(max_length=400)),
                ('Q_category', models.CharField(max_length=400)),
                ('Q_text', models.CharField(max_length=400, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='Q_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crcsite.Question'),
        ),
    ]
