# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='Value',
            field=models.IntegerField(null=True),
        ),
    ]
