# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcsite', '0003_auto_20171024_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Q_category',
            field=models.CharField(choices=[('Heredity and medical history', 'Heredity and medical history'), ('Behavioral factors', 'Behavioral factors'), ('Factors decrease risks', 'Factors decrease risks')], max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='Q_type',
            field=models.CharField(choices=[('Choice', 'Choice'), ('Fill', 'Fill')], default='Choice', max_length=100),
        ),
    ]
