# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crcsite', '0004_auto_20171024_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Q_type',
            field=models.CharField(choices=[('Choice', 'Choice'), ('Fill', 'Fill')], max_length=100),
        ),
    ]
