# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crcsite', '0005_auto_20171024_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Q_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='A', to='crcsite.Question'),
        ),
    ]
